# Generated by Django 4.2 on 2023-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
