# Generated by Django 4.2 on 2023-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_alter_url_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
