# Buildspec runs in the build stage of your pipeline.
version: 0.2
phases:
  install:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.33.1 -O copilot-linux
      - chmod +x ./copilot-linux
  build:
    commands:
      - ls -la core
      - echo "Generate .env file"
      - cp ./.env.dev core/.env
      - ls -la
      - ls -la core
      - cat core/.env

      - echo "Run your tests"
      # - make test
  post_build:
    commands:
      - ls -l
      - export COLOR="false"
      - export CI="true"
      - pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/shorturl-dev/manifest.yml | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
      - stages=$(echo $pipeline | jq -r '.stages[].name')
      - ./copilot-linux env package -n 'shorturl-dev' --output-dir './infrastructure' --upload-assets --force;
      - ./copilot-linux svc package -n 'shorturl-dev' -e 'shorturl-dev' --output-dir './infrastructure' --upload-assets;
      - ls -lah ./infrastructure
artifacts:
  files:
    - "infrastructure/*"
